apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saas-framework-dev

resources:
  - ../../base

namePrefix: dev-

replicas:
  - name: api-gateway
    count: 1
  - name: auth-service
    count: 1
  - name: user-service
    count: 1
  - name: tenant-service
    count: 1
  - name: notification-service
    count: 1
  - name: system-config-service
    count: 1

configMapGenerator:
  - name: env-config
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - MONGODB_DATABASE=saas_dev

images:
  - name: api-gateway
    newName: ghcr.io/vhvcorp/go-api-gateway
    newTag: dev
  - name: auth-service
    newName: ghcr.io/vhvcorp/go-auth-service
    newTag: dev
  - name: user-service
    newName: ghcr.io/vhvcorp/go-user-service
    newTag: dev
  - name: tenant-service
    newName: ghcr.io/vhvcorp/go-tenant-service
    newTag: dev
  - name: notification-service
    newName: ghcr.io/vhvcorp/go-notification-service
    newTag: dev
  - name: system-config-service
    newName: ghcr.io/vhvcorp/go-system-config-service
    newTag: dev
