apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas-services-dev
  namespace: argocd
  labels:
    environment: development
spec:
  project: saas-platform
  
  source:
    repoURL: https://github.com/longvhv/saas-infrastructure
    targetRevision: main
    path: helm/charts/saas-platform
    helm:
      valueFiles:
        - values.dev.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: saas-framework-dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
