apiVersion: v1
kind: Service
metadata:
  name: tenant-mapper
  namespace: saas-framework
  labels:
    app: tenant-mapper
    component: infrastructure
spec:
  selector:
    app: tenant-mapper
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  type: ClusterIP
